<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - run on firefox</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>run on firefox</h1>
<p>
  Test duration: 10.263s
</p>



  <table class="resultsTable">
    <tr><th colspan="3" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">com.nopcommerce.user.Level_15_Report_Allure</td>
      </tr>
            
<tr>
  <td class="method">
                  User_01_Register
      </td>
  <td class="duration">
    2.496s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [Your registration123 completed] but found [Your registration completed]</b></a><br />
    <div class="stackTrace" id="exception-0">
              org.testng.Assert.fail(Assert.java:96)<br />
              org.testng.Assert.failNotEquals(Assert.java:776)<br />
              org.testng.Assert.assertEqualsImpl(Assert.java:137)<br />
              org.testng.Assert.assertEquals(Assert.java:118)<br />
              org.testng.Assert.assertEquals(Assert.java:442)<br />
              commons.BaseTest.verifyEquals(BaseTest.java:117)<br />
              com.nopcommerce.user.Level_15_Report_Allure.User_01_Register(Level_15_Report_Allure.java:58)<br />
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.base/java.lang.reflect.Method.invoke(Method.java:566)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:648)<br />
              org.testng.TestRunner.run(TestRunner.java:505)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:364)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br />
              org.testng.TestNG.runSuites(TestNG.java:1049)<br />
              org.testng.TestNG.run(TestNG.java:1017)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  User_02_Switch_Account
      </td>
  <td class="duration">
    2.806s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">public void com.nopcommerce.user.Level_15_Report_Allure.User_02_Switch_Account(java.lang.reflect.Method)</span><br />
    
        

        <a href="javascript:toggleElement('exception-1', 'block')" title="Click to expand/collapse"><b>java.lang.Throwable: Multiple failures (2):<br/>
Failure 1 of 2<br/>
java.lang.AssertionError: expected [My account1 - Customer info] but found [My account - Customer info]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)<br/>
	at org.testng.Assert.assertEquals(Assert.java:118)<br/>
	at org.testng.Assert.assertEquals(Assert.java:442)<br/>
	at commons.BaseTest.verifyEquals(BaseTest.java:117)<br/>
	at com.nopcommerce.user.Level_15_Report_Allure.User_02_Switch_Account(Level_15_Report_Allure.java:66)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 2 of 2<br/>
java.lang.AssertionError: expected [My account2 - Customer info] but found [My account - Customer info]</b></a><br />
    <div class="stackTrace" id="exception-1">
              org.testng.Assert.fail(Assert.java:96)<br />
              org.testng.Assert.failNotEquals(Assert.java:776)<br />
              org.testng.Assert.assertEqualsImpl(Assert.java:137)<br />
              org.testng.Assert.assertEquals(Assert.java:118)<br />
              org.testng.Assert.assertEquals(Assert.java:442)<br />
              commons.BaseTest.verifyEquals(BaseTest.java:117)<br />
              com.nopcommerce.user.Level_15_Report_Allure.User_02_Switch_Account(Level_15_Report_Allure.java:71)<br />
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.base/java.lang.reflect.Method.invoke(Method.java:566)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:648)<br />
              org.testng.TestRunner.run(TestRunner.java:505)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:364)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br />
              org.testng.TestNG.runSuites(TestNG.java:1049)<br />
              org.testng.TestNG.run(TestNG.java:1017)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
      </table>


  
</body>
</html>
